import type { PrismaClient, Prisma } from "../../generated/prisma/client.js";
import type { CatalogFilters, CatalogInput, CatalogKind, ReadCatalogKind, OrderFilters, ProductionOrderInput, TransformationOrderInput } from "./production.dto.js";
type Db = PrismaClient | Prisma.TransactionClient;
export class ProductionRepository {
  constructor(private readonly db: Db) {}
  async list(kind: ReadCatalogKind, f: CatalogFilters) {
    const where = { ...(f.active === undefined ? {} : { active: f.active }), ...(f.search ? { OR: [{ code: { contains: f.search, mode: "insensitive" as const } }, { name: { contains: f.search, mode: "insensitive" as const } }] } : {}) };
    const skip = ((f.page ?? 1) - 1) * (f.pageSize ?? 20); const take = f.pageSize ?? 20;
    const query = async <T>(delegate: { findMany: (a: object) => Promise<T[]>; count: (a: object) => Promise<number> }) => { const [items, total] = await Promise.all([delegate.findMany({ where, skip, take, orderBy: { code: "asc" } }), delegate.count({ where })]); return { items, pagination: { page: f.page ?? 1, pageSize: take, total, totalPages: Math.ceil(total / take) } }; };
    switch (kind) {
      case "participants": return query(this.db.productionParticipant);
      case "producers": return query(this.db.producer);
      case "grape-varieties": return query(this.db.grapeVariety);
      case "work-types": return query(this.db.workType);
      case "measurement-types": return query(this.db.measurementType);
    }
  }
  async find(kind: CatalogKind, id: string) { switch (kind) { case "participants": return this.db.productionParticipant.findUnique({ where: { id } }); case "producers": return this.db.producer.findUnique({ where: { id } }); case "grape-varieties": return this.db.grapeVariety.findUnique({ where: { id } }); case "work-types": return this.db.workType.findUnique({ where: { id } }); case "measurement-types": return this.db.measurementType.findUnique({ where: { id } }); } }
  async findCode(kind: CatalogKind, code: string) { switch (kind) { case "participants": return this.db.productionParticipant.findUnique({ where: { code } }); case "producers": return this.db.producer.findUnique({ where: { code } }); case "grape-varieties": return this.db.grapeVariety.findUnique({ where: { code } }); case "work-types": return this.db.workType.findUnique({ where: { code } }); case "measurement-types": return this.db.measurementType.findUnique({ where: { code } }); } }
  async create(kind: CatalogKind, data: CatalogInput) { switch (kind) { case "participants": return this.db.productionParticipant.create({ data }); case "producers": return this.db.producer.create({ data: { code: data.code, name: data.name } }); case "grape-varieties": return this.db.grapeVariety.create({ data: { code: data.code, name: data.name } }); case "work-types": return this.db.workType.create({ data: { code: data.code, name: data.name } }); case "measurement-types": return this.db.measurementType.create({ data: { code: data.code, name: data.name } }); } }
  async update(kind: CatalogKind, id: string, data: { name?: string; active?: boolean; userId?: string }) { const clean = { ...(data.name !== undefined ? { name: data.name } : {}), ...(data.active !== undefined ? { active: data.active } : {}), ...(data.userId !== undefined ? { userId: data.userId } : {}) }; const adminClean = { ...(data.name !== undefined ? { name: data.name } : {}), ...(data.active !== undefined ? { active: data.active } : {}) }; switch (kind) { case "participants": return this.db.productionParticipant.update({ where: { id }, data: clean }); case "producers": return this.db.producer.update({ where: { id }, data: clean }); case "grape-varieties": return this.db.grapeVariety.update({ where: { id }, data: clean }); case "work-types": return this.db.workType.update({ where: { id }, data: adminClean }); case "measurement-types": return this.db.measurementType.update({ where: { id }, data: adminClean }); } }
  async listOrders(filters: OrderFilters) { const page = filters.page ?? 1; const pageSize = filters.pageSize ?? 20; const where = filters.status ? { status: filters.status } : {}; const [items, total] = await Promise.all([this.db.productionOrder.findMany({ where, skip: (page - 1) * pageSize, take: pageSize, orderBy: [{ startDate: "desc" }, { code: "asc" }] }), this.db.productionOrder.count({ where })]); return { items, pagination: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findOrder(id: string) { return this.db.productionOrder.findUnique({ where: { id }, include: { transformationOrders: true } }); }
  async createOrder(data: ProductionOrderInput) { return this.db.productionOrder.create({ data: { code: data.code, startDate: data.startDate, ...(data.observations !== undefined ? { observations: data.observations } : {}) } }); }
  async listTransformationOrders(filters: OrderFilters) { const page = filters.page ?? 1; const pageSize = filters.pageSize ?? 20; const where = filters.status ? { status: filters.status } : {}; const [items, total] = await Promise.all([this.db.transformationOrder.findMany({ where, skip: (page - 1) * pageSize, take: pageSize, orderBy: [{ periodStart: "desc" }, { code: "asc" }], include: { productionOrder: true } }), this.db.transformationOrder.count({ where })]); return { items, pagination: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findTransformationOrder(id: string) { return this.db.transformationOrder.findUnique({ where: { id }, include: { productionOrder: true } }); }
  async createTransformationOrder(data: TransformationOrderInput) { return this.db.transformationOrder.create({ data: { code: data.code, productionOrderId: data.productionOrderId, periodStart: data.periodStart, ...(data.periodEnd !== undefined ? { periodEnd: data.periodEnd } : {}), ...(data.observations !== undefined ? { observations: data.observations } : {}) } }); }
}