import { Router, type RequestHandler } from "express";
import { z } from "zod";
import { requirePermission } from "../../core/access-control/authorization.middleware.js";
import { authenticate, resolveCurrentUser } from "../../core/auth/auth.middleware.js";
import type { TokenVerifier } from "../../core/auth/auth.types.js";
import type { UserRepository } from "../../core/users/user.repository.js";
import { validateRequest } from "../../shared/http/validate-request.js";
import { ProductionController } from "./production.controller.js";
   import { catalogInputSchema, administrativeCatalogInputSchema, catalogUpdateSchema, idParamsSchema, listSchema, customDefinitionSchema, customDefinitionUpdateSchema, customValueSchema, orderListSchema, productionOrderCreateSchema, transformationOrderCreateSchema, batchListSchema, containerCreateSchema, containerUpdateSchema, workListSchema, workCreateSchema, workCorrectionSchema, workInputSchema, workInputReversalSchema, grapeReceptionSchema, grapeReceptionListSchema, measurementCreateSchema, measurementListSchema, transformationCreateSchema, transformationListSchema, releaseBatchSchema, measurementCorrectionSchema, receptionCorrectionSchema } from "./production.schema.js";
import type { ProductionService } from "./production.service.js";
const manage: Record<string, string> = { participants: "production:participant_manage", producers: "production:producer_manage", "grape-varieties": "production:grape_variety_manage", "work-types": "production:work_type_manage", "measurement-types": "production:measurement_type_manage" };
const transformationPermissions: RequestHandler = (req, res, next) => {
  const requireTransform = requirePermission("production:transformation_create");
  requireTransform(req, res, error => {
    if (error) return next(error);
    if (Array.isArray(req.body?.losses) && req.body.losses.length > 0) return requirePermission("production:loss_create")(req, res, next);
    next();
  });
};
export function createProductionRouter(verifier: TokenVerifier, users: UserRepository, service: ProductionService) {
  const router = Router(); const auth = [authenticate(verifier), resolveCurrentUser(users)] as const;
  for (const kind of ["participants", "producers", "grape-varieties", "work-types", "measurement-types"] as const) {
    const r = Router(); const permission = manage[kind]!; const controller = new ProductionController(service, kind);
    r.get("/", ...auth, requirePermission("production:read"), validateRequest({ query: listSchema }), controller.list);
    r.post("/", ...auth, requirePermission(permission), validateRequest({ body: kind === "participants" ? catalogInputSchema : administrativeCatalogInputSchema }), controller.create);
    r.patch("/:id", ...auth, requirePermission(permission), validateRequest({ params: idParamsSchema, body: catalogUpdateSchema }), controller.update);
    r.post("/:id/activate", ...auth, requirePermission(permission), validateRequest({ params: idParamsSchema }), controller.activate);
    r.post("/:id/deactivate", ...auth, requirePermission(permission), validateRequest({ params: idParamsSchema }), controller.deactivate);
    router.use(`/${kind}`, r);
  }
  const controller = new ProductionController(service, "participants");
  router.get("/orders", ...auth, requirePermission("production:read"), validateRequest({ query: orderListSchema }), controller.listOrders);
  router.get("/orders/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getOrder);
  router.post("/orders", ...auth, requirePermission("production:order_create"), validateRequest({ body: productionOrderCreateSchema }), controller.createOrder);
  router.post("/orders/:id/close", ...auth, requirePermission("production:order_close"), validateRequest({ params: idParamsSchema }), controller.closeOrder);
  router.get("/transformation-orders", ...auth, requirePermission("production:read"), validateRequest({ query: orderListSchema }), controller.listTransformationOrders);
  router.get("/transformation-orders/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getTransformationOrder);
  router.post("/transformation-orders", ...auth, requirePermission("production:transformation_order_create"), validateRequest({ body: transformationOrderCreateSchema }), controller.createTransformationOrder);
  router.post("/transformation-orders/:id/close", ...auth, requirePermission("production:transformation_order_close"), validateRequest({ params: idParamsSchema }), controller.closeTransformationOrder);
  router.get("/transformations", ...auth, requirePermission("production:read"), validateRequest({ query: transformationListSchema }), controller.listTransformations);
  router.get("/transformations/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getTransformation);
  router.post("/transformations", ...auth, validateRequest({ body: transformationCreateSchema }), transformationPermissions, controller.createTransformation);
  router.get("/batches", ...auth, requirePermission("production:read"), validateRequest({ query: batchListSchema }), controller.listBatches);
  router.get("/batches/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getBatch);
  router.get("/batches/:id/trace", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getBatchTrace);
  router.get("/batches/:id/balance", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getBatchBalance);
  router.post("/batches/:id/release-to-inventory", ...auth, requirePermission("production:inventory_release"), validateRequest({ params: idParamsSchema, body: releaseBatchSchema }), controller.releaseBatchToInventory);
  router.get("/containers", ...auth, requirePermission("production:read"), controller.listContainers);
  router.get("/containers/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getContainer);
  router.get("/containers/:id/occupancies", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getContainerOccupancies);
  router.get("/containers/:id/movements", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getContainerMovements);
  router.post("/containers", ...auth, requirePermission("production:container_manage"), validateRequest({ body: containerCreateSchema }), controller.createContainer);
  router.patch("/containers/:id", ...auth, requirePermission("production:container_manage"), validateRequest({ params: idParamsSchema, body: containerUpdateSchema }), controller.updateContainer);
  router.post("/containers/:id/activate", ...auth, requirePermission("production:container_manage"), validateRequest({ params: idParamsSchema }), controller.activateContainer);
  router.post("/containers/:id/deactivate", ...auth, requirePermission("production:container_manage"), validateRequest({ params: idParamsSchema }), controller.deactivateContainer);
  router.get("/custom-fields/definitions", ...auth, requirePermission("production:read"), controller.definitions);
  router.get("/works", ...auth, requirePermission("production:read"), validateRequest({ query: workListSchema }), controller.listWorks);
  router.get("/works/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getWork);
  router.post("/works", ...auth, requirePermission("production:work_create"), validateRequest({ body: workCreateSchema }), controller.createWork);
  router.post("/works/:id/inputs", ...auth, requirePermission("production:work_input_create"), validateRequest({ params: idParamsSchema, body: workInputSchema }), controller.createWorkInput);
  router.post("/works/:workId/inputs/:inputId/reverse", ...auth, requirePermission("production:work_input_reverse"), validateRequest({ params: z.object({ workId: z.string().uuid(), inputId: z.string().uuid() }), body: workInputReversalSchema }), controller.reverseWorkInput);
  router.get("/grape-receptions", ...auth, requirePermission("production:read"), validateRequest({ query: grapeReceptionListSchema }), controller.listReceptions);
  router.get("/grape-receptions/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getReception);
  router.post("/grape-receptions", ...auth, requirePermission("production:reception_create"), validateRequest({ body: grapeReceptionSchema }), controller.createReception);
  router.post("/grape-receptions/:id/corrections", ...auth, requirePermission("production:reception_correct"), validateRequest({ params: idParamsSchema, body: receptionCorrectionSchema }), controller.correctReception);
  router.get("/measurements", ...auth, requirePermission("production:read"), validateRequest({ query: measurementListSchema }), controller.listMeasurements);
  router.get("/measurements/:id", ...auth, requirePermission("production:read"), validateRequest({ params: idParamsSchema }), controller.getMeasurement);
  router.post("/measurements", ...auth, requirePermission("production:measurement_create"), validateRequest({ body: measurementCreateSchema }), controller.createMeasurement);
  router.post("/measurements/:id/corrections", ...auth, requirePermission("production:measurement_correct"), validateRequest({ params: idParamsSchema, body: measurementCorrectionSchema }), controller.correctMeasurement);
  router.post("/works/:id/corrections", ...auth, requirePermission("production:work_correct"), validateRequest({ params: idParamsSchema, body: workCorrectionSchema }), controller.correctWork);
  router.post("/custom-fields/definitions", ...auth, requirePermission("production:custom_fields_manage"), validateRequest({ body: customDefinitionSchema }), controller.createDefinition);
  router.patch("/custom-fields/definitions/:id", ...auth, requirePermission("production:custom_fields_manage"), validateRequest({ params: idParamsSchema, body: customDefinitionUpdateSchema }), controller.updateDefinition);
  router.post("/custom-fields/definitions/:id/activate", ...auth, requirePermission("production:custom_fields_manage"), validateRequest({ params: idParamsSchema }), controller.activateDefinition);
  router.post("/custom-fields/definitions/:id/deactivate", ...auth, requirePermission("production:custom_fields_manage"), validateRequest({ params: idParamsSchema }), controller.deactivateDefinition);
  router.put("/custom-fields/values", ...auth, requirePermission("production:custom_fields_manage"), validateRequest({ body: customValueSchema }), controller.setValue);
  return router;
}