import type { NextFunction, Request, Response } from "express";
import { buildAuthenticatedAuditContext } from "../../shared/http/audit-context.js";
import { catalogInputSchema, administrativeCatalogInputSchema, catalogUpdateSchema, idParamsSchema, listSchema, customDefinitionSchema, customDefinitionUpdateSchema, customValueSchema } from "./production.schema.js";
import type { CatalogKind, ReadCatalogKind } from "./production.dto.js";
import type { ProductionService } from "./production.service.js";
export class ProductionController {
  constructor(private readonly service: ProductionService, private readonly kind: ReadCatalogKind) {}
  list = async (req: Request, res: Response, next: NextFunction) => { try { const q = listSchema.parse(req.query); const filters = { page: q.page, pageSize: q.pageSize, ...(q.search !== undefined ? { search: q.search } : {}), ...(q.active !== undefined ? { active: q.active } : {}) }; const r = await this.service.list(this.kind, filters); res.json({ data: r.items, meta: r.pagination }); } catch (e) { next(e); } };
  create = async (req: Request, res: Response, next: NextFunction) => { try { const data = (this.kind === "participants" ? catalogInputSchema.parse(req.body) : administrativeCatalogInputSchema.parse(req.body)); const item = await this.service.create(this.kind as CatalogKind, data, buildAuthenticatedAuditContext(req, res)); res.status(201).json({ data: item }); } catch (e) { next(e); } };
  update = async (req: Request, res: Response, next: NextFunction) => { try { const parsed = catalogUpdateSchema.parse(req.body); const data = parsed.name !== undefined ? { name: parsed.name } : {}; const item = await this.service.update(this.kind as CatalogKind, idParamsSchema.parse(req.params).id, data, buildAuthenticatedAuditContext(req, res)); res.json({ data: item }); } catch (e) { next(e); } };
  activate = async (req: Request, res: Response, next: NextFunction) => { try { const item = await this.service.setActive(this.kind as CatalogKind, idParamsSchema.parse(req.params).id, true, buildAuthenticatedAuditContext(req, res)); res.json({ data: item }); } catch (e) { next(e); } };
  deactivate = async (req: Request, res: Response, next: NextFunction) => { try { const item = await this.service.setActive(this.kind as CatalogKind, idParamsSchema.parse(req.params).id, false, buildAuthenticatedAuditContext(req, res)); res.json({ data: item }); } catch (e) { next(e); } };
  definitions = async (req: Request, res: Response, next: NextFunction) => { try { res.json({ data: await this.service.listDefinitions({}) }); } catch (e) { next(e); } };
  createDefinition = async (req: Request, res: Response, next: NextFunction) => { try { const p = customDefinitionSchema.parse(req.body); const { options, ...base } = p; const data = options === undefined ? base : { ...base, options }; res.status(201).json({ data: await this.service.createDefinition(data, buildAuthenticatedAuditContext(req, res)) }); } catch (e) { next(e); } };
  updateDefinition = async (req: Request, res: Response, next: NextFunction) => { try { const p = customDefinitionUpdateSchema.parse(req.body); const { options, ...base } = p; const data = options === undefined ? base : { ...base, options }; res.json({ data: await this.service.updateDefinition(idParamsSchema.parse(req.params).id, data, buildAuthenticatedAuditContext(req, res)) }); } catch (e) { next(e); } };
  activateDefinition = async (req: Request, res: Response, next: NextFunction) => { try { res.json({ data: await this.service.setDefinitionActive(idParamsSchema.parse(req.params).id, true, buildAuthenticatedAuditContext(req, res)) }); } catch (e) { next(e); } };
  deactivateDefinition = async (req: Request, res: Response, next: NextFunction) => { try { res.json({ data: await this.service.setDefinitionActive(idParamsSchema.parse(req.params).id, false, buildAuthenticatedAuditContext(req, res)) }); } catch (e) { next(e); } };
  setValue = async (req: Request, res: Response, next: NextFunction) => { try { res.json({ data: await this.service.setValue(customValueSchema.parse(req.body), buildAuthenticatedAuditContext(req, res)) }); } catch (e) { next(e); } };
}