import { Prisma } from "../../generated/prisma/client.js";
import type { PrismaClient } from "../../generated/prisma/client.js";
import { AppError } from "../../shared/errors/app-error.js";

export interface ProductionBatchTraceDto {
  rootBatchId: string;
  batches: Array<{ id: string; code: string; productionOrderId: string; articuloId: string; unit: string; createdAt: string; observations: string | null; version: number; article: { id: string; codigo: string; nombre: string; clasificacion: string; unidadMedida: string } | null; order: { id: string; code: string; status: string; startDate: string; observations: string | null; closedAt: string | null }; balance: Record<string, string | number> | null }>;
  lineage: Array<{ id: string; parentBatchId: string; childBatchId: string; quantity: string | null; unit: string | null; operationKey: string; createdAt: string }>;
  ledger: Array<{ id: string; productionBatchId: string; entryType: string; quantity: string; unit: string; occurredAt: string; operationKey: string; metadata: JsonValue | null }>;
  releases: Array<{ releaseId: string; productionBatchId: string; quantity: string; unit: string; warehouseId: string; inventoryLotId: string; inventoryMovementId: string; operationKey: string; actorUserId: string; occurredAt: string; status: "ACTIVE"|"REVERSED"; reversal: { operationKey: string; reason: string; inventoryMovementId: string; occurredAt: string } | null }>;
  receptions: Array<{ id: string; productionOrderId: string; producerId: string | null; receivedAt: string; status: string; observations: string | null; version: number; items: Array<{ id: string; productionBatchId: string; grapeVarietyId: string; articuloId: string; quantity: string; unit: string }>; corrections: CorrectionDto[] }>;
  works: Array<{ id: string; productionOrderId: string; transformationOrderId: string | null; workTypeId: string; performedAt: string; observations: string | null; version: number; workType: { id: string; code: string; name: string }; batches: string[]; containers: string[]; participants: Array<{ participantId: string; role: string | null }>; inputs: Array<{ id: string; productionWorkId: string; articuloId: string; article: { id: string; codigo: string; nombre: string } | null; warehouseId: string | null; warehouse: { id: string; codigo: string; nombre: string } | null; inventoryLotId: string | null; quantity: string; unit: string; inventoryMovementId: string | null; operationKey: string | null; status: "ACTIVE"|"REVERSED"; reversedAt: string | null; reversalInventoryMovementId: string | null; reversalOperationKey: string | null; reversalReason: string | null }>; corrections: CorrectionDto[] }>;
  measurements: Array<{ id: string; measurementTypeId: string; value: string; unit: string; measuredAt: string; observations: string | null; productionBatchId: string | null; productionContainerId: string | null; productionWorkId: string | null; participantId: string | null; corrections: CorrectionDto[] }>;
  transformations: Array<{ id: string; productionOrderId: string; transformationOrderId: string | null; productionWorkId: string | null; actorUserId: string; operationKey: string; performedAt: string; observations: string | null; inputs: Array<{ productionBatchId: string; quantity: string; unit: string }>; outputs: Array<{ productionBatchId: string; quantity: string; unit: string }>; losses: Array<{ id: string; productionBatchId: string | null; quantity: string; unit: string; occurredAt: string }> }>;
  losses: Array<{ id: string; productionBatchId: string | null; quantity: string; unit: string; occurredAt: string; observations: string | null }>;
  containers: Array<{ id: string; code: string; name: string | null; type: string | null; location: string | null; material: string | null; capacity: string; capacityUnit: string; status: string; observations: string | null; occupancies: Array<{ id: string; batchId: string; quantity: string; unit: string; openedAt: string; closedAt: string | null }>; movements: Array<{ id: string; movementType: string; sourceContainerId: string | null; destinationContainerId: string; sourceBatchId: string; destinationBatchId: string | null; quantity: string; unit: string; occurredAt: string; productionWorkId: string | null; observations: string | null; actorUserId: string; createdAt: string }> }>;
  inventory: { lots: Array<{ id: string; lotCode: string; articuloId: string; article: { id: string; codigo: string; nombre: string } | null; classification: string; fechaIngreso: string; observations: string | null; originProductionBatchId: string | null }>; movements: Array<{ id: string; type: string; source: string; reason: string | null; articuloId: string; article: { id: string; codigo: string; nombre: string } | null; warehouseId: string; warehouse: { id: string; codigo: string; nombre: string } | null; destinationWarehouseId: string | null; destinationWarehouse: { id: string; codigo: string; nombre: string } | null; inventoryLotId: string | null; quantity: string; unit: string; stockBefore: string; resultingStock: string; createdAt: string }>; stocks: Array<{ id: string; warehouseId: string; warehouse: { id: string; codigo: string; nombre: string } | null; articuloId: string; article: { id: string; codigo: string; nombre: string } | null; inventoryLotId: string | null; quantity: string; unit: string }> };
  warnings: string[];
}
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject { [key: string]: JsonValue; }
export interface CorrectionDto { id: string; field: string; previousValue: JsonValue; newValue: JsonValue; reason: string; correctedAt: string; actorUserId: string; fromVersion: number; toVersion: number; }
const iso = (value: Date) => value.toISOString();
const decimal = (value: Prisma.Decimal) => value.toString();
const localJson = (value: Prisma.JsonValue): JsonValue => {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(item => localJson(item));
  return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, localJson(item ?? null)]));
};
const traceMetadata = (value: Prisma.JsonValue | null): JsonValue | null => {
  if (!value || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(item => traceMetadata(item)) as JsonValue[];
  return Object.fromEntries(Object.entries(value).filter(([key]) => key !== "requestHash").map(([key, item]) => [key, traceMetadata(item ?? null)]));
};
const correction = (row: { id: string; field: string; previousValue: Prisma.JsonValue; newValue: Prisma.JsonValue; reason: string; correctedAt: Date; actorUserId: string; fromVersion: number; toVersion: number }): CorrectionDto => ({ id: row.id, field: row.field, previousValue: localJson(row.previousValue), newValue: localJson(row.newValue), reason: row.reason, correctedAt: iso(row.correctedAt), actorUserId: row.actorUserId, fromVersion: row.fromVersion, toVersion: row.toVersion });

export class ProductionTraceService {
  constructor(private readonly prisma: PrismaClient) {}
  async get(id: string): Promise<ProductionBatchTraceDto> {
    const root = await this.prisma.productionBatch.findUnique({ where: { id } });
    if (!root) throw new AppError("BATCH_NOT_FOUND", "Production batch not found", 404);
    const depths = new Map<string, number>([[id, 0]]); const queue = [id]; const edgeMap = new Map<string, { id: string; parentBatchId: string; childBatchId: string; quantity: Prisma.Decimal | null; unit: string | null; operationKey: string; createdAt: Date }>();
    while (queue.length) {
      const layer = queue.splice(0); const layerDepth = Math.max(...layer.map(batchId => depths.get(batchId) ?? 0));
      const edges = await this.prisma.productionBatchLineage.findMany({ where: { OR: [{ parentBatchId: { in: layer } }, { childBatchId: { in: layer } }] }, orderBy: [{ createdAt: "asc" }, { id: "asc" }] });
      for (const edge of edges) {
        edgeMap.set(edge.id, edge);
        for (const next of [edge.parentBatchId, edge.childBatchId]) if (!depths.has(next)) { const depth = layerDepth + 1; if (depth > 100) throw new AppError("TRACE_LIMIT_EXCEEDED", "Trace exceeds the maximum depth", 422); depths.set(next, depth); queue.push(next); }
        if (depths.size > 1000) throw new AppError("TRACE_LIMIT_EXCEEDED", "Trace exceeds the maximum number of batches", 422);
      }
    }
    const ids = [...depths.keys()];
    const batches = await this.prisma.productionBatch.findMany({ where: { id: { in: ids } }, include: { productionOrder: true, balance: true } });
    const ledgers = await this.prisma.productionBatchLedgerEntry.findMany({ where: { productionBatchId: { in: ids } }, orderBy: [{ occurredAt: "asc" }, { id: "asc" }] });
    const receptions = await this.prisma.grapeReception.findMany({ where: { items: { some: { productionBatchId: { in: ids } } } }, include: { items: true, corrections: { orderBy: { toVersion: "asc" } } } });
    const transformations = await this.prisma.transformation.findMany({ where: { OR: [{ inputs: { some: { productionBatchId: { in: ids } } } }, { outputs: { some: { productionBatchId: { in: ids } } } }] }, include: { inputs: true, outputs: true, losses: true }, orderBy: [{ performedAt: "asc" }, { id: "asc" }] });
    const workLinks = await this.prisma.productionWorkBatch.findMany({ where: { productionBatchId: { in: ids } }, select: { productionWorkId: true } });
    const workIds = [...new Set(workLinks.map(row => row.productionWorkId).concat(transformations.flatMap(row => [row.productionWorkId, ...row.losses.map(loss => loss.productionWorkId)]).filter((value): value is string => value !== null)))];
    const works = await this.prisma.productionWork.findMany({ where: { id: { in: workIds } }, include: { workType: true, batches: true, containers: true, participants: true, inputs: true, corrections: { orderBy: { toVersion: "asc" } } } });
    const graphOccupancies = await this.prisma.productionContainerOccupancy.findMany({ where: { batchId: { in: ids } }, select: { containerId: true, batchId: true, openedAt: true, closedAt: true } });
    const occupancyContainerIds = graphOccupancies.map(row => row.containerId);
    const workContainerIds = (await this.prisma.productionWorkContainer.findMany({ where: { productionWorkId: { in: workIds } }, select: { productionContainerId: true } })).map(row => row.productionContainerId);
    const containerIds = [...new Set(occupancyContainerIds.concat(workContainerIds))];
    const movementScope = [{ sourceBatchId: { in: ids } }, { destinationBatchId: { in: ids } }, ...(workIds.length ? [{ productionWorkId: { in: workIds } }] : [])];
    const containers = await this.prisma.productionContainer.findMany({ where: { id: { in: containerIds } }, include: { occupancies: { where: { batchId: { in: ids } } }, movementsFrom: { where: { OR: movementScope } }, movementsTo: { where: { OR: movementScope } } } });
    const measurementScope = [{ productionBatchId: { in: ids } }, { productionWorkId: { in: workIds } }, ...graphOccupancies.map(row => ({ productionContainerId: row.containerId, measuredAt: { gte: row.openedAt, ...(row.closedAt ? { lte: row.closedAt } : {}) } }))];
    const measurements = await this.prisma.productionMeasurement.findMany({ where: { OR: measurementScope }, include: { corrections: { orderBy: { toVersion: "asc" } } }, orderBy: [{ measuredAt: "asc" }, { id: "asc" }] });
    const losses = await this.prisma.productionLoss.findMany({ where: { OR: [{ productionBatchId: { in: ids } }, { productionWorkId: { in: workIds } }, { transformationId: { in: transformations.map(row => row.id) } }] }, orderBy: [{ occurredAt: "asc" }, { id: "asc" }] });
    const workInputLotIds = works.flatMap(work => work.inputs.map(input => input.inventoryLotId).filter((value): value is string => value !== null));
    const lotIds = [...new Set(workInputLotIds)];
    const lots = await this.prisma.inventoryLot.findMany({ where: { OR: [{ originProductionBatchId: { in: ids } }, { id: { in: lotIds } }] }, orderBy: { id: "asc" } });
    const includedLotIds = lots.map(lot => lot.id);
    const workInputMovementIds = works.flatMap(work => work.inputs.flatMap(input => [input.inventoryMovementId, input.reversalInventoryMovementId]).filter((value): value is string => value !== null));
    const movementIds = [...new Set(workInputMovementIds)];
    const movementRows = await this.prisma.inventoryMovement.findMany({ where: { OR: [{ inventoryLotId: { in: includedLotIds } }, { id: { in: movementIds } }] }, orderBy: [{ createdAt: "asc" }, { id: "asc" }] });
    const releases = await this.prisma.productionInventoryRelease.findMany({ where: { productionBatchId: { in: ids } }, include: { reversal: true }, orderBy: [{ occurredAt: "asc" }, { id: "asc" }] });
    const stocks = await this.prisma.inventoryStock.findMany({ where: { inventoryLotId: { in: includedLotIds } }, orderBy: { id: "asc" } });
    const articleIds = [...new Set(batches.map(batch => batch.articuloId).concat(works.flatMap(work => work.inputs.map(input => input.articuloId)), lots.map(lot => lot.articuloId), movementRows.map(row => row.articuloId), stocks.map(row => row.articuloId)))];
    const articles = await this.prisma.articulo.findMany({ where: { id: { in: articleIds } } });
    const articlesById = new Map(articles.map(article => [article.id, article]));
    const warehouseIds = [...new Set(works.flatMap(work => work.inputs.map(input => input.warehouseId).filter((value): value is string => value !== null)).concat(movementRows.flatMap(row => [row.warehouseId, row.destinationWarehouseId]).filter((value): value is string => value !== null), stocks.map(row => row.warehouseId)))];
    const warehouses = await this.prisma.warehouse.findMany({ where: { id: { in: warehouseIds } } });
    const warehousesById = new Map(warehouses.map(warehouse => [warehouse.id, warehouse]));
    const knownLotIds = new Set(includedLotIds);
    const warnings = batches.filter(batch => !articlesById.has(batch.articuloId)).map(batch => `Batch ${batch.id} references missing Articulo ${batch.articuloId}`).concat(ledgers.flatMap(entry => {
      if (entry.entryType !== "TRANSFERRED_TO_INVENTORY") return [];
      if (!entry.metadata || typeof entry.metadata !== "object" || !("inventoryLotId" in entry.metadata) || typeof entry.metadata.inventoryLotId !== "string") return [`Ledger ${entry.id} has malformed inventory linkage`];
      return knownLotIds.has(entry.metadata.inventoryLotId) ? [] : [`Ledger ${entry.id} references missing InventoryLot ${entry.metadata.inventoryLotId}`];
    }));
    return {
      rootBatchId: id,
      batches: batches.sort((a, b) => a.id.localeCompare(b.id)).map(batch => { const balance = batch.balance; const article = articlesById.get(batch.articuloId); return { id: batch.id, code: batch.code, productionOrderId: batch.productionOrderId, articuloId: batch.articuloId, unit: batch.unit, createdAt: iso(batch.createdAt), observations: batch.observations, version: batch.version, article: article ? { id: article.id, codigo: article.codigo, nombre: article.nombre, clasificacion: article.clasificacion, unidadMedida: article.unidadMedida } : null, order: { id: batch.productionOrder.id, code: batch.productionOrder.code, status: batch.productionOrder.status, startDate: iso(batch.productionOrder.startDate), observations: batch.productionOrder.observations, closedAt: batch.productionOrder.closedAt ? iso(batch.productionOrder.closedAt) : null }, balance: balance ? Object.fromEntries(["generated","consumed","separated","lost","transferredToInventory","available"].map(key => [key, decimal(balance[key as keyof typeof balance] as Prisma.Decimal)])) : null }; }),
      lineage: [...edgeMap.values()].sort((a, b) => a.id.localeCompare(b.id)).map(edge => ({ id: edge.id, parentBatchId: edge.parentBatchId, childBatchId: edge.childBatchId, quantity: edge.quantity ? decimal(edge.quantity) : null, unit: edge.unit, operationKey: edge.operationKey, createdAt: iso(edge.createdAt) })),
      ledger: ledgers.map(entry => ({ id: entry.id, productionBatchId: entry.productionBatchId, entryType: entry.entryType, quantity: decimal(entry.quantity), unit: entry.unit, occurredAt: iso(entry.occurredAt), operationKey: entry.operationKey, metadata: traceMetadata(entry.metadata) })),
      releases: releases.map(row => ({ releaseId: row.id, productionBatchId: row.productionBatchId, quantity: decimal(row.quantity), unit: row.unit, warehouseId: row.warehouseId, inventoryLotId: row.inventoryLotId, inventoryMovementId: row.inventoryMovementId, operationKey: row.operationKey, actorUserId: row.actorUserId, occurredAt: iso(row.occurredAt), status: row.reversal ? "REVERSED" : "ACTIVE", reversal: row.reversal ? { operationKey: row.reversal.operationKey, reason: row.reversal.reason, inventoryMovementId: row.reversal.inventoryMovementId, occurredAt: iso(row.reversal.occurredAt) } : null })),
      receptions: receptions.map(row => ({ id: row.id, productionOrderId: row.productionOrderId, producerId: row.producerId, receivedAt: iso(row.receivedAt), status: row.status, observations: row.observations, version: row.version, items: row.items.map(item => ({ id: item.id, productionBatchId: item.productionBatchId, grapeVarietyId: item.grapeVarietyId, articuloId: item.articuloId, quantity: decimal(item.quantity), unit: item.unit })), corrections: row.corrections.map(correction) })),
       works: works.map(work => ({ id: work.id, productionOrderId: work.productionOrderId, transformationOrderId: work.transformationOrderId, workTypeId: work.workTypeId, performedAt: iso(work.performedAt), observations: work.observations, version: work.version, workType: { id: work.workType.id, code: work.workType.code, name: work.workType.name }, batches: work.batches.map(row => row.productionBatchId).sort(), containers: work.containers.map(row => row.productionContainerId).sort(), participants: work.participants.map(row => ({ participantId: row.productionParticipantId, role: row.role })), inputs: work.inputs.map(row => ({ id: row.id, productionWorkId: row.productionWorkId, articuloId: row.articuloId, article: articlesById.get(row.articuloId) ? { id: row.articuloId, codigo: articlesById.get(row.articuloId)!.codigo, nombre: articlesById.get(row.articuloId)!.nombre } : null, warehouseId: row.warehouseId, warehouse: row.warehouseId && warehousesById.get(row.warehouseId) ? { id: row.warehouseId, codigo: warehousesById.get(row.warehouseId)!.codigo, nombre: warehousesById.get(row.warehouseId)!.nombre } : null, inventoryLotId: row.inventoryLotId, quantity: decimal(row.quantity), unit: row.unit, inventoryMovementId: row.inventoryMovementId, operationKey: row.operationKey, status: row.reversedAt ? "REVERSED" : "ACTIVE", reversedAt: row.reversedAt?.toISOString() ?? null, reversalInventoryMovementId: row.reversalInventoryMovementId, reversalOperationKey: row.reversalOperationKey, reversalReason: row.reversalReason })), corrections: work.corrections.map(correction) })),
      measurements: measurements.map(row => ({ id: row.id, measurementTypeId: row.measurementTypeId, value: decimal(row.value), unit: row.unit, measuredAt: iso(row.measuredAt), observations: row.observations, productionBatchId: row.productionBatchId, productionContainerId: row.productionContainerId, productionWorkId: row.productionWorkId, participantId: row.participantId, corrections: row.corrections.map(correction) })),
       transformations: transformations.map(row => ({ id: row.id, productionOrderId: row.productionOrderId, transformationOrderId: row.transformationOrderId, productionWorkId: row.productionWorkId, actorUserId: row.actorUserId, operationKey: row.operationKey, performedAt: iso(row.performedAt), observations: row.observations, inputs: row.inputs.map(input => ({ productionBatchId: input.productionBatchId, quantity: decimal(input.quantity), unit: input.unit })), outputs: row.outputs.map(output => ({ productionBatchId: output.productionBatchId, quantity: decimal(output.quantity), unit: output.unit })), losses: row.losses.map(loss => ({ id: loss.id, productionBatchId: loss.productionBatchId, quantity: decimal(loss.quantity), unit: loss.unit, occurredAt: iso(loss.occurredAt) })) })),
      losses: losses.map(loss => ({ id: loss.id, productionBatchId: loss.productionBatchId, quantity: decimal(loss.quantity), unit: loss.unit, occurredAt: iso(loss.occurredAt), observations: loss.observations })),
       containers: containers.map(container => ({ id: container.id, code: container.code, name: container.name, type: container.type, location: container.location, material: container.material, capacity: decimal(container.capacity), capacityUnit: container.capacityUnit, status: container.status, observations: container.observations, occupancies: container.occupancies.filter(row => ids.includes(row.batchId)).map(row => ({ id: row.id, batchId: row.batchId, quantity: decimal(row.quantity), unit: row.unit, openedAt: iso(row.openedAt), closedAt: row.closedAt ? iso(row.closedAt) : null })), movements: [...new Map([...container.movementsFrom, ...container.movementsTo].filter(row => ids.includes(row.sourceBatchId) || (row.destinationBatchId !== null && ids.includes(row.destinationBatchId)) || (row.productionWorkId !== null && workIds.includes(row.productionWorkId))).map(row => [row.id, row])).values()].sort((a, b) => a.id.localeCompare(b.id)).map(row => ({ id: row.id, movementType: row.movementType, sourceContainerId: row.sourceContainerId, destinationContainerId: row.destinationContainerId, sourceBatchId: row.sourceBatchId, destinationBatchId: row.destinationBatchId, quantity: decimal(row.quantity), unit: row.unit, occurredAt: iso(row.occurredAt), productionWorkId: row.productionWorkId, observations: row.observations, actorUserId: row.actorUserId, createdAt: iso(row.createdAt) })) })),
       inventory: { lots: lots.map(lot => ({ id: lot.id, lotCode: lot.lotCode, articuloId: lot.articuloId, article: articlesById.get(lot.articuloId) ? { id: lot.articuloId, codigo: articlesById.get(lot.articuloId)!.codigo, nombre: articlesById.get(lot.articuloId)!.nombre } : null, classification: lot.classification, fechaIngreso: iso(lot.fechaIngreso), observations: lot.observations, originProductionBatchId: lot.originProductionBatchId })), movements: movementRows.map(row => ({ id: row.id, type: row.type, source: row.source, reason: row.reason, articuloId: row.articuloId, article: articlesById.get(row.articuloId) ? { id: row.articuloId, codigo: articlesById.get(row.articuloId)!.codigo, nombre: articlesById.get(row.articuloId)!.nombre } : null, warehouseId: row.warehouseId, warehouse: warehousesById.get(row.warehouseId) ? { id: row.warehouseId, codigo: warehousesById.get(row.warehouseId)!.codigo, nombre: warehousesById.get(row.warehouseId)!.nombre } : null, destinationWarehouseId: row.destinationWarehouseId, destinationWarehouse: row.destinationWarehouseId && warehousesById.get(row.destinationWarehouseId) ? { id: row.destinationWarehouseId, codigo: warehousesById.get(row.destinationWarehouseId)!.codigo, nombre: warehousesById.get(row.destinationWarehouseId)!.nombre } : null, inventoryLotId: row.inventoryLotId, quantity: decimal(row.quantity), unit: row.unit, stockBefore: decimal(row.stockBefore), resultingStock: decimal(row.resultingStock), createdAt: iso(row.createdAt) })), stocks: stocks.map(row => ({ id: row.id, warehouseId: row.warehouseId, warehouse: warehousesById.get(row.warehouseId) ? { id: row.warehouseId, codigo: warehousesById.get(row.warehouseId)!.codigo, nombre: warehousesById.get(row.warehouseId)!.nombre } : null, articuloId: row.articuloId, article: articlesById.get(row.articuloId) ? { id: row.articuloId, codigo: articlesById.get(row.articuloId)!.codigo, nombre: articlesById.get(row.articuloId)!.nombre } : null, inventoryLotId: row.inventoryLotId, quantity: decimal(row.quantity), unit: row.unit })) },
      warnings,
    };
  }
}