import { useMutation, useQuery, useQueryClient, type UseMutationOptions, type UseQueryOptions } from '@tanstack/react-query';
import { ApiError } from '@/lib/api/api-error';
import { activateWarehouse, adjustStock, classifyLot, createWarehouse, deactivateWarehouse, getAllActiveWarehouses, getAvailableStock, getLot, getStock, getWarehouse, getWarehouses, registerInbound, registerOutbound, transferStock, updateWarehouse } from './inventory.api';
import { inventoryKeys } from './inventory.keys';
import type { AdjustmentInput, ClassifyLotInput, CreateWarehouseInput, IdempotentCommand, MovementInput, StockFilters, TransferInput, UpdateWarehouseInput, WarehouseListFilters } from '../types/inventory.types';
const retryQuery = (count: number, error: Error) => count < 1 && (!(error instanceof ApiError) || error.status === 0 || error.status >= 500);
type QueryOptions<T> = Omit<UseQueryOptions<T, Error>, 'queryKey' | 'queryFn'>;
export function useWarehouses(filters: WarehouseListFilters = {}, options?: QueryOptions<Awaited<ReturnType<typeof getWarehouses>>>) { return useQuery({ ...options, queryKey: inventoryKeys.warehouseList(filters), queryFn: ({ signal }) => getWarehouses(filters, signal), retry: options?.retry ?? retryQuery }); }
export function useWarehouse(id: string, options?: QueryOptions<Awaited<ReturnType<typeof getWarehouse>>>) { return useQuery({ ...options, queryKey: inventoryKeys.warehouse(id), queryFn: ({ signal }) => getWarehouse(id, signal), enabled: Boolean(id) && (options?.enabled ?? true), retry: options?.retry ?? retryQuery }); }
export function useActiveWarehouses(options?: QueryOptions<Awaited<ReturnType<typeof getAllActiveWarehouses>>>) { return useQuery({ ...options, queryKey: inventoryKeys.activeWarehouses(), queryFn: ({ signal }) => getAllActiveWarehouses(signal), retry: options?.retry ?? retryQuery }); }
export function useStock(filters: StockFilters, options?: QueryOptions<Awaited<ReturnType<typeof getStock>>>) { return useQuery({ ...options, queryKey: inventoryKeys.stockValue(filters), queryFn: ({ signal }) => getStock(filters, signal), enabled: Boolean(filters.warehouseId && filters.articuloId) && (options?.enabled ?? true), retry: options?.retry ?? retryQuery }); }
export function useAvailableStock(filters: StockFilters, options?: QueryOptions<Awaited<ReturnType<typeof getAvailableStock>>>) { return useQuery({ ...options, queryKey: inventoryKeys.availableValue(filters), queryFn: ({ signal }) => getAvailableStock(filters, signal), enabled: Boolean(filters.warehouseId && filters.articuloId) && (options?.enabled ?? true), retry: options?.retry ?? retryQuery }); }
export function useInventoryLot(id: string, options?: QueryOptions<Awaited<ReturnType<typeof getLot>>>) { return useQuery({ ...options, queryKey: inventoryKeys.lot(id), queryFn: ({ signal }) => getLot(id, signal), enabled: Boolean(id) && (options?.enabled ?? true), retry: options?.retry ?? retryQuery }); }
function commandMutation<T, V>(fn: (value: V) => Promise<T>, options?: Omit<UseMutationOptions<T, Error, V>, 'mutationFn'>) { return { ...options, mutationFn: fn, retry: false as const }; }
function invalidateStock(qc: ReturnType<typeof useQueryClient>, warehouseId: string, articuloId: string) {
  const hasStockFilters = (value: unknown): value is StockFilters => typeof value === 'object' && value !== null
    && 'warehouseId' in value && 'articuloId' in value
    && value.warehouseId === warehouseId && value.articuloId === articuloId;
  const matches = (query: { queryKey: readonly unknown[] }) => {
    const key = query.queryKey;
    if (key[0] !== 'inventory' || (key[1] !== 'stock' && key[1] !== 'available')) return false;
    return key.slice(2).some((part) => hasStockFilters(part));
  };
  return qc.invalidateQueries({ predicate: matches });
}
function warehouseMutation<T, V>(fn: (v: V) => Promise<T>, id: (v: V) => string, options?: Omit<UseMutationOptions<T, Error, V>, 'mutationFn'>) { const qc = useQueryClient(); return useMutation({ ...commandMutation(fn, options), onSuccess: async (data, variables, context, mutationContext) => { await Promise.all([qc.invalidateQueries({ queryKey: inventoryKeys.warehouseLists() }), qc.invalidateQueries({ queryKey: inventoryKeys.warehouse(id(variables)) }), qc.invalidateQueries({ queryKey: inventoryKeys.activeWarehouses() })]); await options?.onSuccess?.(data, variables, context, mutationContext); } }); }
export const useCreateWarehouse = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof createWarehouse>>, Error, CreateWarehouseInput>, 'mutationFn'>) => { const qc = useQueryClient(); return useMutation({ ...commandMutation(createWarehouse, options), onSuccess: async (d, v, c, mc) => { await Promise.all([qc.invalidateQueries({ queryKey: inventoryKeys.warehouseLists() }), qc.invalidateQueries({ queryKey: inventoryKeys.activeWarehouses() })]); await options?.onSuccess?.(d, v, c, mc); } }); };
export const useUpdateWarehouse = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof updateWarehouse>>, Error, { id: string; input: UpdateWarehouseInput }>, 'mutationFn'>) => warehouseMutation(({ id, input }) => updateWarehouse(id, input), (v) => v.id, options);
export const useActivateWarehouse = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof activateWarehouse>>, Error, string>, 'mutationFn'>) => warehouseMutation(activateWarehouse, (id) => id, options);
export const useDeactivateWarehouse = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof deactivateWarehouse>>, Error, string>, 'mutationFn'>) => warehouseMutation(deactivateWarehouse, (id) => id, options);
function movementMutation<T, V>(fn: (v: V) => Promise<T>, affected: (qc: ReturnType<typeof useQueryClient>, v: V) => Promise<unknown>[], options?: Omit<UseMutationOptions<T, Error, V>, 'mutationFn'>) { const qc = useQueryClient(); return useMutation({ ...commandMutation(fn, options), onSuccess: async (d, v, c, mc) => { await Promise.all(affected(qc, v)); await options?.onSuccess?.(d, v, c, mc); } }); }
const affectedMovement = (qc: ReturnType<typeof useQueryClient>, v: IdempotentCommand<MovementInput>) => { const i = v.input; return invalidateStock(qc, i.warehouseId, i.articuloId); };
export const useRegisterInbound = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof registerInbound>>, Error, IdempotentCommand<MovementInput>>, 'mutationFn'>) => movementMutation(registerInbound, (qc, v) => [affectedMovement(qc, v)], options);
export const useRegisterOutbound = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof registerOutbound>>, Error, IdempotentCommand<MovementInput>>, 'mutationFn'>) => movementMutation(registerOutbound, (qc, v) => [affectedMovement(qc, v)], options);
export const useTransferStock = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof transferStock>>, Error, IdempotentCommand<TransferInput>>, 'mutationFn'>) => movementMutation(transferStock, (qc, v) => { const i = v.input; return [invalidateStock(qc, i.sourceWarehouseId, i.articuloId), invalidateStock(qc, i.destinationWarehouseId, i.articuloId)]; }, options);
export const useAdjustStock = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof adjustStock>>, Error, IdempotentCommand<AdjustmentInput>>, 'mutationFn'>) => movementMutation(adjustStock, (qc, v) => [affectedMovement(qc, v)], options);
export const useClassifyLot = (options?: Omit<UseMutationOptions<Awaited<ReturnType<typeof classifyLot>>, Error, { inventoryLotId: string; command: IdempotentCommand<ClassifyLotInput> }>, 'mutationFn'>) => { const qc = useQueryClient(); return useMutation({ ...commandMutation(({ inventoryLotId, command }) => classifyLot(inventoryLotId, command), options), onSuccess: async (d, v, c, mc) => { await qc.invalidateQueries({ queryKey: inventoryKeys.lot(v.inventoryLotId) }); await options?.onSuccess?.(d, v, c, mc); } }); };