CREATE TYPE "CustomFieldEntityType" AS ENUM ('PRODUCER', 'GRAPE_VARIETY', 'GRAPE_RECEPTION');
CREATE TYPE "CustomFieldDataType" AS ENUM ('TEXT', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'SELECT');
CREATE TABLE "production_work_types" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_work_types_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_measurement_types" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_measurement_types_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_participants" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "user_id" UUID, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_participants_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_producers" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_producers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_grape_varieties" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_grape_varieties_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_custom_field_definitions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "entity_type" "CustomFieldEntityType" NOT NULL, "code" TEXT NOT NULL, "label" TEXT NOT NULL, "data_type" "CustomFieldDataType" NOT NULL, "required" BOOLEAN NOT NULL DEFAULT false, "active" BOOLEAN NOT NULL DEFAULT true, "options" JSONB, "display_order" INTEGER NOT NULL DEFAULT 0, "created_by_user_id" UUID NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_custom_field_definitions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_custom_field_values" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "definition_id" UUID NOT NULL, "entity_type" "CustomFieldEntityType" NOT NULL, "entity_id" UUID NOT NULL, "text_value" TEXT, "integer_value" INTEGER, "decimal_value" DECIMAL(18,6), "boolean_value" BOOLEAN, "date_value" TIMESTAMP(3), "select_value" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_custom_field_values_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "production_work_types_code_key" ON "production_work_types"("code");
CREATE UNIQUE INDEX "production_measurement_types_code_key" ON "production_measurement_types"("code");
CREATE UNIQUE INDEX "production_participants_code_key" ON "production_participants"("code");
CREATE UNIQUE INDEX "production_producers_code_key" ON "production_producers"("code");
CREATE UNIQUE INDEX "production_grape_varieties_code_key" ON "production_grape_varieties"("code");
CREATE INDEX "production_work_types_active_idx" ON "production_work_types"("active");
CREATE INDEX "production_measurement_types_active_idx" ON "production_measurement_types"("active");
CREATE UNIQUE INDEX "production_custom_field_definitions_entity_type_code_key" ON "production_custom_field_definitions"("entity_type","code");
CREATE UNIQUE INDEX "production_custom_field_values_definition_id_entity_id_key" ON "production_custom_field_values"("definition_id","entity_id");
CREATE INDEX "production_participants_active_idx" ON "production_participants"("active");
CREATE INDEX "production_participants_user_id_idx" ON "production_participants"("user_id");
CREATE INDEX "production_producers_active_idx" ON "production_producers"("active");
CREATE INDEX "production_grape_varieties_active_idx" ON "production_grape_varieties"("active");
CREATE INDEX "production_custom_field_definitions_list_idx" ON "production_custom_field_definitions"("entity_type","active","display_order");
CREATE INDEX "production_custom_field_values_entity_idx" ON "production_custom_field_values"("entity_type","entity_id");
CREATE INDEX "production_custom_field_values_definition_idx" ON "production_custom_field_values"("definition_id");
ALTER TABLE "production_custom_field_values" ADD CONSTRAINT "production_custom_field_values_definition_id_fkey" FOREIGN KEY ("definition_id") REFERENCES "production_custom_field_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "production_custom_field_values" ADD CONSTRAINT "production_custom_field_values_exactly_one_value" CHECK (num_nonnulls("text_value", "integer_value", "decimal_value", "boolean_value", "date_value", "select_value") = 1);