import type { BatchListFilters, CatalogFilters, ProductionOrderFilters, ReceptionListFilters, TransformationOrderFilters, WorkListFilters, MeasurementListFilters, TransformationListFilters } from '../types/production.types';
export const productionKeys = {
  all: ['production'] as const,
  participants: () => [...productionKeys.all, 'participants'] as const,
  participantLists: () => [...productionKeys.participants(), 'list'] as const,
  participantList: (filters: CatalogFilters = {}) => [...productionKeys.participantLists(), filters] as const,
  participant: (id: string) => [...productionKeys.participants(), 'detail', id] as const,
  producers: () => [...productionKeys.all, 'producers'] as const,
  producerLists: () => [...productionKeys.producers(), 'list'] as const,
  producerList: (filters: CatalogFilters = {}) => [...productionKeys.producerLists(), filters] as const,
  producer: (id: string) => [...productionKeys.producers(), 'detail', id] as const,
  grapeVarieties: () => [...productionKeys.all, 'grapeVarieties'] as const,
  grapeVarietyLists: () => [...productionKeys.grapeVarieties(), 'list'] as const,
  grapeVarietyList: (filters: CatalogFilters = {}) => [...productionKeys.grapeVarietyLists(), filters] as const,
  grapeVariety: (id: string) => [...productionKeys.grapeVarieties(), 'detail', id] as const,
  workTypes: () => [...productionKeys.all, 'workTypes'] as const,
  workTypeLists: () => [...productionKeys.workTypes(), 'list'] as const,
  workTypeList: (filters: CatalogFilters = {}) => [...productionKeys.workTypeLists(), filters] as const,
  workType: (id: string) => [...productionKeys.workTypes(), 'detail', id] as const,
  measurementTypes: () => [...productionKeys.all, 'measurementTypes'] as const,
  measurementTypeLists: () => [...productionKeys.measurementTypes(), 'list'] as const,
  measurementTypeList: (filters: CatalogFilters = {}) => [...productionKeys.measurementTypeLists(), filters] as const,
  measurementType: (id: string) => [...productionKeys.measurementTypes(), 'detail', id] as const,
  customFields: () => [...productionKeys.all, 'customFields'] as const,
  customFieldDefinitions: () => [...productionKeys.customFields(), 'definitions'] as const,
  customFieldValues: () => [...productionKeys.customFields(), 'values'] as const,
  orders: () => [...productionKeys.all, 'orders'] as const,
  orderLists: () => [...productionKeys.orders(), 'list'] as const,
  orderList: (filters: ProductionOrderFilters = {}) => [...productionKeys.orderLists(), filters] as const,
  order: (id: string) => [...productionKeys.orders(), 'detail', id] as const,
  transformationOrders: () => [...productionKeys.all, 'transformationOrders'] as const,
  transformationOrderLists: () => [...productionKeys.transformationOrders(), 'list'] as const,
  transformationOrderList: (filters: TransformationOrderFilters = {}) => [...productionKeys.transformationOrderLists(), filters] as const,
  transformationOrder: (id: string) => [...productionKeys.transformationOrders(), 'detail', id] as const,
  receptions: () => [...productionKeys.all, 'receptions'] as const,
  receptionLists: () => [...productionKeys.receptions(), 'list'] as const,
  receptionList: (filters: ReceptionListFilters = {}) => [...productionKeys.receptionLists(), filters] as const,
  reception: (id: string) => [...productionKeys.receptions(), 'detail', id] as const,
  batches: () => [...productionKeys.all, 'batches'] as const,
  batchLists: () => [...productionKeys.batches(), 'list'] as const,
  batchList: (filters: BatchListFilters = {}) => [...productionKeys.batchLists(), filters] as const,
  batch: (id: string) => [...productionKeys.batches(), 'detail', id] as const,
  batchTrace: (id: string) => ['production', 'trace', id] as const,
  batchBalance: (id: string) => [...productionKeys.batches(), 'balance', id] as const,
  batchReleases: (id: string) => [...productionKeys.batches(), 'releases', id] as const,
  inventoryReleaseWarehouses: () => [...productionKeys.all, 'inventoryReleaseWarehouses'] as const,
  containers: () => [...productionKeys.all, 'containers'] as const,
  container: (id: string) => [...productionKeys.containers(), 'detail', id] as const,
  works: () => [...productionKeys.all, 'works'] as const,
  workLists: () => [...productionKeys.works(), 'list'] as const,
  workList: (filters: WorkListFilters = {}) => [...productionKeys.workLists(), filters] as const,
  work: (id: string) => [...productionKeys.works(), 'detail', id] as const,
  measurements: () => [...productionKeys.all, 'measurements'] as const,
  measurementLists: () => [...productionKeys.measurements(), 'list'] as const,
  measurementList: (filters: MeasurementListFilters = {}) => [...productionKeys.measurementLists(), filters] as const,
  measurement: (id: string) => [...productionKeys.measurements(), 'detail', id] as const,
  transformations: () => [...productionKeys.all, 'transformations'] as const,
  transformationLists: () => [...productionKeys.transformations(), 'list'] as const,
  transformationList: (filters: TransformationListFilters = {}) => [...productionKeys.transformationLists(), filters] as const,
  transformationDetail: (id: string) => [...productionKeys.transformations(), 'detail', id] as const,
};